### ISSUE TITLE
Default Nightingale layout.html

### ISSUE THREAD

**Issue by jdbrew** [NHSLeadership/nhs-prototyping-kit#19]
Currently `./app/views/layouts.html` and `./app/views/includes/head.html` extend pages.

Improve based on @p5uln Nightingale Sketch designs.

**Comment by chriscoffee** [comment]
I'm using this as my base for the changes I've been working on as they incorporate a lot of what's mentioned but extends them further.

**Comment by jdbrew** [comment]
Ok so some of these are optimisations on the way to a base layout. on reflection, could have had some ticket break-out. 
Oh well. We are where we are. 
And we are doing good.
Some great enhancements thanks to @chriscoffee
